services:
  backend:
    environment:
      - branch
      - name
      - token
      - domain
      - supabasekey
      - supabaseurl
      - jwtpriv
      - bigdatacloudkey
    build: ./Backend
  frontend:
    environment:
      - branch
      - VITE_SUPABASE_URL
      - VITE_SUPABASE_KEY
      - VITE_GMAPSAPI
    expose:
      - "80"
    build:
      context: ./Frontend
      args:
      - VITE_DOMAIN=${VITE_DOMAIN}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_KEY=${VITE_SUPABASE_KEY}
      - VITE_GMAPSAPI=${VITE_GMAPSAPI}
networks:
  default:
    name: backend
